"""Radiance ``.cal`` projection function generators.

Three projection modes are supported:

* ``uv``     – mesh UV passthrough (Radiance 6.0, ``Lu``/``Lv``).  This is the
               primary path for any mesh with embedded UVs.
* ``planar`` – fallback planar projection on a chosen axis pair.
* ``box``    – triplanar projection driven by surface normal.

Functions return the raw ``.cal`` file text.
"""

from __future__ import annotations

from typing import Literal

PlanarAxis = Literal["xy", "xz", "yz"]


_HEADER = (
    "{{ Generated by pbr2rad - projection mode: {mode} }}\n"
    "{{ Arguments exposed to .rad file: u v }}\n"
)


def uv_passthrough() -> str:
    """Mesh UV passthrough.  Uses ``Lu``/``Lv`` from the mesh primitive."""
    return (
        _HEADER.format(mode="mesh UV (Lu/Lv)")
        + "u = Lu;\n"
        + "v = Lv;\n"
    )


def planar(
    axis: PlanarAxis = "xy",
    *,
    u_scale: float = 1.0,
    v_scale: float = 1.0,
    u_offset: float = 0.0,
    v_offset: float = 0.0,
) -> str:
    """Planar projection on ``axis`` (``xy``/``xz``/``yz``).

    Scales in world units: ``u_scale = 1/texture_width_meters``.
    """
    u_src, v_src = {
        "xy": ("Px", "Py"),
        "xz": ("Px", "Pz"),
        "yz": ("Py", "Pz"),
    }[axis]
    return (
        _HEADER.format(mode=f"planar {axis.upper()}")
        + f"u_scale : {u_scale:g};\n"
        + f"v_scale : {v_scale:g};\n"
        + f"u_offset : {u_offset:g};\n"
        + f"v_offset : {v_offset:g};\n"
        + f"u = mod({u_src} * u_scale + u_offset, 1);\n"
        + f"v = mod({v_src} * v_scale + v_offset, 1);\n"
    )


def box(*, u_scale: float = 1.0, v_scale: float = 1.0) -> str:
    """Triplanar / box projection driven by the dominant normal axis.

    * |Nz| dominant → XY plane
    * |Nx| dominant → YZ plane
    * |Ny| dominant → XZ plane
    """
    return (
        _HEADER.format(mode="box / triplanar")
        + f"u_scale : {u_scale:g};\n"
        + f"v_scale : {v_scale:g};\n"
        + "abs_nx = abs(Nx);\n"
        + "abs_ny = abs(Ny);\n"
        + "abs_nz = abs(Nz);\n"
        + "nx_dom = if(abs_nx - abs_ny, if(abs_nx - abs_nz, 1, 0), 0);\n"
        + "nz_dom = if(abs_nz - abs_nx, if(abs_nz - abs_ny, 1, 0), 0);\n"
        + "{ ny dominant is the remaining case }\n"
        + "u_raw = if(nx_dom - 0.5, Py, if(nz_dom - 0.5, Px, Px));\n"
        + "v_raw = if(nx_dom - 0.5, Pz, if(nz_dom - 0.5, Py, Pz));\n"
        + "u = mod(u_raw * u_scale, 1);\n"
        + "v = mod(v_raw * v_scale, 1);\n"
    )


def generate(
    mode: str,
    *,
    u_scale: float = 1.0,
    v_scale: float = 1.0,
    u_offset: float = 0.0,
    v_offset: float = 0.0,
    axis: PlanarAxis = "xy",
) -> str:
    """Dispatch helper used by the CLI."""
    if mode == "uv":
        return uv_passthrough()
    if mode == "planar":
        return planar(
            axis,
            u_scale=u_scale,
            v_scale=v_scale,
            u_offset=u_offset,
            v_offset=v_offset,
        )
    if mode == "box":
        return box(u_scale=u_scale, v_scale=v_scale)
    raise ValueError(f"unknown projection mode: {mode!r}")
