"""Normal map conversion for Radiance ``texdata`` perturbation.

Converts a PBR normal map (PNG, OpenGL or DirectX convention) into:

* Three Radiance ``.dat`` data files (one per R/G/B channel, normalised 0..1).
* A ``.cal`` file that samples the ``.dat`` files and computes surface-normal
  perturbation deltas (dx, dy, dz) for use with the ``texdata`` primitive.
"""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image


def _read_channel_f(img: Image.Image, channel: int) -> list[float]:
    """Extract one channel from an image as a list of 0..1 floats.

    Handles both 8-bit (L/RGB) and 16-bit (I;16) images.
    """
    mode = img.mode

    if mode == "I;16":
        # 16-bit single-channel — raw bytes, little-endian unsigned shorts
        data = img.tobytes()
        pixels = struct.unpack(f"<{len(data) // 2}H", data)
        return [p / 65535.0 for p in pixels]

    # For multi-channel images, split and take the requested channel
    if mode == "RGB":
        bands = img.split()
        band = bands[channel]
    elif mode == "L":
        band = img
    else:
        # Force to RGB and extract
        bands = img.convert("RGB").split()
        band = bands[channel]

    data = band.tobytes()
    return [b / 255.0 for b in data]


def write_dat_2d(path: Path, data: list[float], width: int, height: int) -> None:
    """Write a 2D Radiance ``.dat`` data file.

    The file format is::

        2
        0 1 <width>
        0 1 <height>
        <data values, row-major>

    ``data`` contains ``width * height`` float values in row-major order
    (top-left to bottom-right, matching image scanline order).
    """
    if len(data) != width * height:
        raise ValueError(
            f"data length {len(data)} does not match {width}x{height}"
        )
    path = Path(path)

    lines = [
        "2",
        f"0\t1\t{width}",
        f"0\t1\t{height}",
    ]

    # Write data in rows.  Values are rounded to 4 decimal places
    # (sufficient for 8/16-bit source data) to keep file sizes compact
    # while preserving precision for Radiance's bilinear interpolation.
    for row in range(height):
        row_vals = data[row * width : (row + 1) * width]
        lines.append("\t".join(f"{v:.3f}" for v in row_vals))

    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def convert_normal_to_dat(
    src: Path,
    out_dir: Path,
    name: str,
) -> tuple[str, str, str, int, int]:
    """Convert a normal map PNG into three Radiance ``.dat`` files.

    Returns ``(r_dat_name, g_dat_name, b_dat_name, width, height)``
    where ``*_dat_name`` is the bare filename (no directory).
    """
    img = Image.open(src)
    width, height = img.size

    # Extract R, G, B channels as 0..1 floats
    if img.mode == "I;16":
        # Single-channel 16-bit — treat as grayscale (unusual for normals)
        ch_r = _read_channel_f(img, 0)
        ch_g = ch_r[:]
        ch_b = ch_r[:]
    else:
        img_rgb = img.convert("RGB")
        ch_r = _read_channel_f(img_rgb, 0)
        ch_g = _read_channel_f(img_rgb, 1)
        ch_b = _read_channel_f(img_rgb, 2)

    r_name = f"{name}_nor_r.dat"
    g_name = f"{name}_nor_g.dat"
    b_name = f"{name}_nor_b.dat"

    out_dir = Path(out_dir)
    write_dat_2d(out_dir / r_name, ch_r, width, height)
    write_dat_2d(out_dir / g_name, ch_g, width, height)
    write_dat_2d(out_dir / b_name, ch_b, width, height)

    return r_name, g_name, b_name, width, height


def generate_normal_cal(
    name: str,
    *,
    is_dx: bool = False,
) -> str:
    """Generate a ``.cal`` file for normal-map perturbation via ``texdata``.

    The ``texdata`` primitive passes interpolated values from the three
    ``.dat`` files as arguments to the perturbation functions.  Each
    function receives ``(dx, dy, dz)`` — the sampled values from the
    R, G, B data files respectively.

    The ``.dat`` files store channel values in [0, 1].  We remap to
    [-1, +1] normal-vector range, then output perturbation deltas.
    ``A1`` (the first real argument from the texdata definition) controls
    bump intensity.

    Parameters
    ----------
    name:
        Material name (for comments).
    is_dx:
        If True, flip the Y component (DirectX convention).
    """
    flip_y = -1 if is_dx else 1

    return (
        f"{{ Normal perturbation for {name} - generated by pbr2rad }}\n"
        f"{{ Convention: {'DirectX (Y flipped)' if is_dx else 'OpenGL'} }}\n"
        "{ A1 = bump intensity (from texdata real args) }\n"
        "\n"
        "{ Each function receives (dx,dy,dz) = sampled R,G,B from .dat files }\n"
        "{ Convert from [0,1] data range to [-1,+1] normal range }\n"
        f"dx_func(r,g,b) = A1 * (2*r - 1);\n"
        f"dy_func(r,g,b) = A1 * {flip_y} * (2*g - 1);\n"
        f"dz_func(r,g,b) = A1 * (2*b - 1 - 1);\n"
    )


def detect_convention(maps: dict[str, Path]) -> str:
    """Detect normal map convention from discovered channel keys.

    Returns ``"gl"`` (OpenGL, Y+) or ``"dx"`` (DirectX, Y-).
    Defaults to ``"gl"`` when ambiguous.
    """
    if "normal_dx" in maps and "normal_gl" not in maps:
        return "dx"
    return "gl"


# ---------------------------------------------------------------------------
# Spatially varying roughness (brightdata)
# ---------------------------------------------------------------------------

def convert_roughness_to_dat(
    src: Path,
    out_dir: Path,
    name: str,
) -> tuple[str, int, int]:
    """Convert a roughness map PNG into a single Radiance ``.dat`` file.

    The roughness map is single-channel (grayscale).  Values are stored
    as 0..1 floats in the ``.dat`` file.

    Returns ``(dat_name, width, height)``.
    """
    img = Image.open(src)
    width, height = img.size

    # Read as grayscale 0..1
    mode = img.mode
    if mode in ("I;16", "I"):
        data = img.tobytes()
        pixels = struct.unpack(f"<{len(data) // 2}H", data)
        channel = [p / 65535.0 for p in pixels]
    else:
        gray = img.convert("L")
        raw = gray.tobytes()
        channel = [b / 255.0 for b in raw]

    dat_name = f"{name}_rough.dat"
    write_dat_2d(Path(out_dir) / dat_name, channel, width, height)
    return dat_name, width, height


def generate_roughness_cal(name: str) -> str:
    """Generate a ``.cal`` file for roughness-driven specular modulation.

    Used with ``brightdata``.  The function receives the sampled roughness
    value and converts it to a specular attenuation factor:

    * roughness=0 (smooth) → factor=1 (full specular)
    * roughness=1 (rough)  → factor=(1 - A1) (reduced specular)

    ``A1`` (from the brightdata real args) controls the modulation depth.
    """
    return (
        f"{{ Roughness-driven specular modulation for {name} - generated by pbr2rad }}\n"
        "{ A1 = modulation depth (from brightdata real args) }\n"
        "\n"
        "{ Invert roughness to specular brightness: smooth=bright, rough=dim }\n"
        "rough_func(v) = 1 - A1 * v;\n"
    )
