"""Radiance ``.rad`` material definition generator.

Maps PBR parameters to a Radiance ``plastic`` (dielectric) or ``metal``
primitive with a ``colorpict`` albedo pattern.

PBR → Radiance mapping used here:

* Albedo PNG/JPG (sRGB)        → ``colorpict`` on ``.hdr`` (linear)
* Roughness (mean, 0..1)       → Radiance roughness ≈ roughness²
                                 (perceptual → microfacet α)
* Metalness (mean, 0..1)       → ``plastic`` below 0.5, ``metal`` at/above
* Specular reflectance         → dielectric F0 ≈ 0.04 (plastic specularity
                                 argument); for ``metal`` the specularity is
                                 driven by the albedo itself, so we pass 1.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class MaterialParams:
    name: str
    hdr_file: str
    cal_file: str
    roughness: float = 0.5  # perceptual, 0..1
    metalness: float = 0.0  # 0..1
    specularity: float | None = None  # override; None → auto (0.05 plastic / 1 metal)

    def as_primitive(self) -> str:
        """Return ``"plastic"`` or ``"metal"`` based on metalness."""
        return "metal" if self.metalness >= 0.5 else "plastic"


def _rad_roughness(perceptual: float) -> float:
    """Perceptual roughness (0..1) → Radiance microfacet roughness."""
    r = max(0.0, min(1.0, perceptual))
    return round(r * r, 4)


def _rad_specularity(params: MaterialParams) -> float:
    if params.specularity is not None:
        return params.specularity
    # Radiance ``metal`` uses the pattern colour as specular reflectance, so
    # the specularity argument is 1.  ``plastic`` uses a scalar specular on
    # top of the diffuse pattern — 0.05 is a good neutral dielectric F0.
    return 1.0 if params.metalness >= 0.5 else 0.05


def generate(params: MaterialParams) -> str:
    """Generate a Radiance ``.rad`` scene snippet for one material."""
    prim = params.as_primitive()
    spec = _rad_specularity(params)
    rough = _rad_roughness(params.roughness)
    pat = f"{params.name}_pat"

    lines = [
        f"# Generated by pbr2rad - {params.name}",
        f"# primitive: {prim}  metalness: {params.metalness:.3f}"
        f"  roughness: {params.roughness:.3f}",
        "",
        f"void colorpict {pat}",
        f"7 red green blue {params.hdr_file} {params.cal_file} u v",
        "0",
        "0",
        "",
        f"{pat} {prim} {params.name}",
        "0",
        "0",
        f"5 1 1 1 {spec:g} {rough:g}",
        "",
    ]
    return "\n".join(lines)
