"""Radiance ``.rad`` material definition generator.

Maps PBR parameters to a Radiance ``plastic`` (dielectric) or ``metal``
primitive with a ``colorpict`` albedo pattern.

PBR → Radiance mapping used here:

* Albedo PNG/JPG (sRGB)        → ``colorpict`` on ``.hdr`` (linear)
* Roughness (mean, 0..1)       → Radiance roughness ≈ roughness²
                                 (perceptual → microfacet α)
* Metalness (mean, 0..1)       → ``plastic`` below 0.5, ``metal`` at/above
* Specular reflectance         → 0.05 for plastic (slightly above the
                                 textbook dielectric F0 of 0.04; chosen so
                                 typical materials read with a visible
                                 sheen in Radiance). For ``metal`` the
                                 specularity is driven by the albedo
                                 itself, so we pass 1.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class MaterialParams:
    name: str
    hdr_file: str
    cal_file: str
    roughness: float = 0.5  # perceptual, 0..1
    metalness: float = 0.0  # 0..1
    specularity: float | None = None  # override; None → auto (0.05 plastic / 1 metal)

    # Normal map (texdata) support — all three must be set, or all None.
    normal_dat_r: str | None = None
    normal_dat_g: str | None = None
    normal_dat_b: str | None = None
    normal_cal_file: str | None = None
    bump_scale: float = 1.0
    normal_is_dx: bool = False

    # Spatially varying roughness (brightdata) support.
    rough_dat: str | None = None
    rough_cal_file: str | None = None
    rough_modulation: float = 0.8  # how much roughness varies specular (0=none, 1=full)

    def as_primitive(self) -> str:
        """Return ``"plastic"`` or ``"metal"`` based on metalness."""
        return "metal" if self.metalness >= 0.5 else "plastic"

    @property
    def has_normal(self) -> bool:
        """True if normal map data files are fully configured.

        Requires all three .dat channels AND the .cal file — a partially
        populated set would emit the literal string ``None`` into the .rad.
        """
        return all(
            x is not None
            for x in (
                self.normal_dat_r,
                self.normal_dat_g,
                self.normal_dat_b,
                self.normal_cal_file,
            )
        )

    @property
    def has_rough_map(self) -> bool:
        """True if spatially varying roughness data is configured."""
        return self.rough_dat is not None


def _rad_roughness(perceptual: float) -> float:
    """Perceptual roughness (0..1) → Radiance microfacet roughness."""
    r = max(0.0, min(1.0, perceptual))
    return round(r * r, 4)


def default_specularity(metalness: float) -> float:
    """Default specular reflectance for the plastic/metal primitive.

    Plastic uses 0.05 as a neutral dielectric F0 added on top of the
    diffuse pattern. Metal uses 1.0 because the pattern colour itself is
    the specular reflectance.
    """
    return 1.0 if metalness >= 0.5 else 0.05


def _rad_specularity(params: MaterialParams) -> float:
    if params.specularity is not None:
        return params.specularity
    return default_specularity(params.metalness)


def generate(params: MaterialParams) -> str:
    """Generate a Radiance ``.rad`` scene snippet for one material.

    If normal map data is configured, a ``texdata`` modifier is inserted
    between the ``colorpict`` pattern and the ``plastic``/``metal`` primitive
    to provide surface-normal perturbation (bump mapping).
    """
    prim = params.as_primitive()
    spec = _rad_specularity(params)
    rough = _rad_roughness(params.roughness)
    pat = f"{params.name}_pat"

    lines = [
        f"# Generated by pbr2rad - {params.name}",
        f"# primitive: {prim}  metalness: {params.metalness:.3f}"
        f"  roughness: {params.roughness:.3f}",
        "",
        f"void colorpict {pat}",
        f"7 red green blue {params.hdr_file} {params.cal_file} u v",
        "0",
        "0",
        "",
    ]

    # Build the modifier chain: colorpict → [texdata] → [brightdata] → material
    # Track the current modifier name as we chain them.
    current_mod = pat

    if params.has_normal:
        tex = f"{params.name}_tex"
        lines += [
            "# Normal map perturbation (texdata)",
            f"{current_mod} texdata {tex}",
            (
                f"9 dx_func dy_func dz_func "
                f"{params.normal_dat_r} {params.normal_dat_g} {params.normal_dat_b} "
                f"{params.normal_cal_file} u v"
            ),
            "0",
            f"1 {params.bump_scale:g}",
            "",
        ]
        current_mod = tex

    if params.has_rough_map:
        rough_id = f"{params.name}_rough"
        lines += [
            "# Spatially varying roughness (brightdata)",
            f"{current_mod} brightdata {rough_id}",
            (
                f"5 rough_func {params.rough_dat} "
                f"{params.rough_cal_file} u v"
            ),
            "0",
            f"1 {params.rough_modulation:g}",
            "",
        ]
        current_mod = rough_id

    lines += [
        f"{current_mod} {prim} {params.name}",
        "0",
        "0",
        f"5 1 1 1 {spec:g} {rough:g}",
        "",
    ]
    return "\n".join(lines)
